### PR TITLE
Bump golang.org/x/net to 0.7.0

### PR DESCRIPTION
**Pull request by bk201**
Bump module golang.org/x/net to 0.7.0.

### CODE REVIEW

**Comment by bk201** [comment]
@brandond Please help take a look, thank you!

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
The CI config needs an update to fix the arm runner. LGTM otherwise.

**Comment by bk201** [comment]
@brandond Do you mean to remove the arm runner and switch to arm64? I see most rancher projects now run arm64 runners.

**Comment by bk201** [comment]
Replaced by https://github.com/rancher/wharfie/pull/19

**Pull request closed without merging**
