### PR TITLE
Fix symlink/hardlink support and add path mapping support to CLI

### PR DESCRIPTION
**Pull request by brandond**
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

### CODE REVIEW

**Comment by brandond** [comment]
@phillipsj the second commit here seems to get me the proper behavior on Windows.

**Review by phillipsj — APPROVED** [review]
LGTM! I assume this replaces my PR?

**Comment by phillipsj** [comment]
@brandond can you please pull a Windows image on Windows to make sure that it works, your test is only doing Linux.

**Comment by dweomer** [comment]
> @brandond can you please pull a Windows image on Windows to make sure that it works, your test is only doing Linux.

@brandond please do pull the Windows image as @phillipsj suggests

**Comment by brandond** [comment]
@phillipsj can you provide a sample Windows image?

**Comment by phillipsj** [comment]
That was the exact use case that was failing. 

```
docker pull rancher/system-agent-installer-rke2:v1.22.3-rc2-rke2r1
```

The path to extract is /Files/bin

**Comment by brandond** [comment]
When in doubt, add tests! Then fix them. Apologies for not having these in the first place. CI doesn't test Windows but I'm building and testing there locally.

**Comment by brandond** [comment]
@phillipsj output on windows:
```console
C:\Users\brandond\repos\github.com\rancher\wharfie>wharfie.exe --debug rancher/system-agent-installer-rke2:v1.22.3-rc2-rke2r1 /Files/bin:C:\temp\bin\
time="2021-11-03T16:47:48-07:00" level=info msg="Extract mapping /Files/bin => C:\\temp\\bin"
time="2021-11-03T16:47:48-07:00" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.22.3-rc2-rke2r1"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Files"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Hives"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Hives/DefaultUser_Delta"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Hives/Sam_Delta"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Hives/Security_Delta"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Hives/Software_Delta"
time="2021-11-03T16:47:49-07:00" level=debug msg="Skipping file Hives/System_Delta"
time="2021-11-03T16:47:50-07:00" level=info msg="Creating directory C:\\temp\\bin"
time="2021-11-03T16:47:50-07:00" level=info msg="Extracting file Files/bin/installer.ps1 to C:\\temp\\bin\\installer.ps1"
time="2021-11-03T16:47:50-07:00" level=info msg="Extracting file Files/bin/rke2.windows-amd64.tar.gz to C:\\temp\\bin\\rke2.windows-amd64.tar.gz"
time="2021-11-03T16:47:52-07:00" level=info msg="Extracting file Files/bin/sha256sum-amd64.txt to C:\\temp\\bin\\sha256sum-amd64.txt"
time="2021-11-03T16:47:52-07:00" level=info msg="Extracting file Files/bin/run.ps1 to C:\\temp\\bin\\run.ps1"
time="2021-11-03T16:47:53-07:00" level=debug msg="Skipping file Files/License.txt"
time="2021-11-03T16:47:53-07:00" level=debug msg="Skipping file Files/ProgramData"
```

**Comment by sirredbeard** [comment]
@brandond Can I ask why this was merged when #4 was already in?

**Comment by brandond** [comment]
#4 didn't pass tests?

**Pull request merged**
